### ISSUE TITLE
ssr2clash的转化不支持origin或auth_sha1_v4协议

### ISSUE THREAD

**Issue by flyingwhitewhale** [frainzy1477/clashrdev#1]
1）项目写的是支持auth_sha1_v4协议。但是几个上述协议的机场，ssr配置经ssr2clash接口转化后生成的配置，节点均无法使用。
把机场的协议改为auth_aes128_md5或auth_aes128_sha1后，重新接口转化生成的配置即可完美使用。
2）origin协议的ssr节点，ssr配置经ssr2clash接口转化后生成的配置，节点均无法使用。
打开配置文件会发现节点如下显示
![{99F7B1B4-ED6D-4E2D-8ABE-709C43D95261} png](https://user-images.githubusercontent.com/30478118/68069527-fdb88f80-fd9b-11e9-9b88-a3780d1d24e5.jpg)

这时只要把type从ssr改为ss，即可正常使用。

不知大佬是否能改进下，谢谢

**Comment by lzdnico** [comment]
这个问题去找写接口的啊。

**Comment by flyingwhitewhale** [comment]
@lzdnico @frainzy1477 与接口无关呀，只要把机场auth_sha1_v4协议改成auth_aes128_md5或auth_aes128_sha1协议就可以正常使用了，说明接口没问题，可能是内核不支持，大佬们看呢
