### ISSUE TITLE
用了新内核每次打开youtube都会出错

### ISSUE THREAD

**Issue by ininolee** [frainzy1477/clashrdev#11]
用的v0.18.0.2  cfwv 0.9.0
每次打开youtube的视频的时候很大概率会出错，刷新一遍就能好

**Comment by carbule-bar** [comment]
应该是断流导致的，表示遇到过同样的问题，有时候是页面加载不完全

**Comment by wangxin6** [comment]
作者把这句话从readme删除了：
`I do not own any of the scripts or code for either clash or clashr, i only apply commit and compile, so use at your own convenience `

**Comment by Maasea** [comment]
查看在加载的时候log 里是不是出现了dial * error: ****
我的解决办法是在配置文件里更改DNS设置：
dns:
  enable: false
  ipv6: false

**Comment by carbule-bar** [comment]
> 查看在加载的时候log 里是不是出现了dial * error: ****
> 我的解决办法是在配置文件里更改DNS设置：
> 
> ```
> dns:
>   enable: false
>   ipv6: false
> ```
> 
> 删除了如下配置：
> 
> ```
> experimental:
>   ignore-resolve-fail: true 
> ```
尝试了，还是没有解决这个问题，也没有这条日志

**Comment by Maasea** [comment]
@carbule-bar 
使用`proxy`模式全局代理呢？检查是不是规则设置问题。
查看clash 目录中的log 文件有无异常。

**Comment by carbule-bar** [comment]
@Maasea 头痛就头痛在全局代理也会出现同样的问题，同时伴随的就是网页打开前会出现网页无法加载的情况或者是网页加载加载不全。配置文件应该不会有问题，是网上订阅直接转换过来的，同时也换过其他配置文件。日志里同样没有发现异常

**Comment by jediseed** [comment]
[warning] dial 🎯 全球直连 error: dial tcp4 ip地址 :8888: connect: connection refused
环境openclash0.36.7+0.18.0.2内核，重复出现如上错误（固定几个地方IP），但是可以正常翻墙。

**Comment by Comah** [comment]
我用的mipsle 挂路由 根本没出现过这条错误Log喔  youtube也正常 偶尔刷新不出来估计是vps断流所致  走的隧道
